version: '3.8'

services:
  back-ventas:
    image: bastian13/back-ventas:latest
    ports:
      - "8081:8081"
    restart: always

  back-despachos:
    image: bastian13/back-despachos:latest
    ports:
      - "8082:8082"
    restart: always

  front-despacho:
    image: bastian13/front-despacho:latest
    user: root
    security_opt:
      - no-new-privileges:false
    read_only: false
    ports:
      - "80:8080"
    restart: always
